name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: github-contribution-grid-snake.svg

      - name: Commit and push SVG
        run: |
          if [ -f github-contribution-grid-snake.svg ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout -B output
            git add github-contribution-grid-snake.svg
            git commit -m "Update contribution snake"
            git push --force --set-upstream origin output
          else
            echo "SVG not generated, skipping commit"
          fi
